#!/bin/bash

# Path to executing script
SCRIPT=$(readlink -e $0)

# Directory housing script
SCRIPTPATH=$(dirname $SCRIPT)

. $SCRIPTPATH/share/common.sh

landscape_exec=$SCRIPTPATH/configure-landscape

# landscape should be available so we register our client
$landscape_exec --admin-email "$LDS_EMAIL" \
                --admin-password "$LDS_PASSWORD" \
                --admin-name "$LDS_NAME" \
                --system-email "$LDS_EMAIL" \
                --maas-host "$MAAS_ENDPOINT" \
                --maas-apikey "$MAAS_APIKEY"
RET=$?

if [ $RET -gt 0 ]; then
    exposeResult "Unable to register against Landscape server, please check your deployment." 1 "false"
fi

hostname=$(unitAddress haproxy 0)
result_message="Access Autopilot: http://$hostname/account/standalone/openstack \n\nlogin: $LDS_EMAIL \npassword: $LDS_PASSWORD"

exposeResult "$result_message" 0 "true"
