#!/bin/bash

# Path to executing script
SCRIPT=$(readlink -e $0)

# Directory housing script
SCRIPTPATH=$(dirname $SCRIPT)

. $SCRIPTPATH/share/common.sh

haproxy=$(unitAddress haproxy 0)

juju ssh -m $JUJU_CONTROLLER:$JUJU_MODEL landscape-server/0 "sudo apt-get -qq update && sudo apt-get -qyf install landscape-api"
CREDS=juju ssh -m $JUJU_CONTROLLER:$JUJU_MODEL landscape-server/0 "LANDSCAPE_API_KEY=\"anonymous\" LANDSCAPE_API_SECRET=\"anonymous\" landscape-api call BootstrapLDS --json admin_email=\"$LDS_EMAIL\" admin_name=\"$LDS_NAME\" admin_password=\"$LDS_PASSWORD\" --uri https://$haproxy/api/ --ssl-ca-file /etc/ssl/certs/landscape_server_ca.crt"
RET=$?

if [ $RET -gt 0 ]; then
    exposeResult "Unable to register against Landscape server, please check your deployment." 1 "false"
fi

LANDSCAPE_API_KEY=$(echo $CREDS|python -c "import sys,yaml; print(yaml.load(sys.stdin))['LANDSCAPE_API_KEY]")
LANDSCAPE_API_SECRET=$(echo $CREDS|python -c "import sys,yaml; print(yaml.load(sys.stdin))['LANDSCAPE_API_SECRET]")

juju ssh -m $JUJU_CONTROLLER:$JUJU_MODEL landscape-server/0 "LANDSCAPE_API_KEY=\"$LANDSCAPE_API_KEY\" LANDSCAPE_API_SECRET=\"$LANDSCAPE_API_SECRET\" landscape-api call RegisterMAASRegionController --json endpoint=\"$MAAS_ENDPOINT\" credentials=\"$MAAS_APIKEY\" --uri https://$haproxy/api/ --ssl-ca-file /etc/ssl/certs/landscape_server_ca.crt"

RET=$?

if [ $RET -gt 0 ]; then
    exposeResult "Unable to register MAAS endpoint against Landscape server, please check your deployment." 1 "false"
fi

result_message="Landscape is now available, to access visit: https://$haproxy/account/standalone/openstack \n\nlogin: $LDS_EMAIL \npassword: $LDS_PASSWORD"

exposeResult "$result_message" 0 "true"

# export LANDSCAPE_API_KEY=$(echo "$output" | python -c "import json; print json.loads(open('/dev/stdin', 
#                'r').read())['LANDSCAPE_API_KEY']")

# landscape-api call BootstrapLDS --json admin_email=stan@example.com admin_name="$ldsver" admin_password=pwd

# LANDSCAPE_API_KEY="anonymous" LANDSCAPE_API_SECRET="anonymous" landscape-api call BootstrapLDS --json admin_email=moo@example.com admin_name="moo" admin_password="password" --uri https://10.0.8.157/api/ --ssl-ca-file /etc/ssl/certs/landscape_server_ca.crt
# {"LANDSCAPE_API_SECRET": "zHwguyk/JE0dIaRNIiqitUNVGm8TuejNsXkYwz08", "LANDSCAPE_API_KEY": "OT70FVBP4HYAKI3ABFCZ"}
