#!/bin/bash

# Path to executing script
SCRIPT=$(readlink -e $0)

# Directory housing script
SCRIPTPATH=$(dirname $SCRIPT)

. $CONJURE_UP_SPELLSDIR/sdk/common.sh

tmpfile=$(mktemp)
$SCRIPTPATH/vars > $tmpfile
cat $SCRIPTPATH/setup-landscape.sh >> $tmpfile

juju scp -m $JUJU_CONTROLLER:$JUJU_MODEL $tmpfile landscape-server/0:setup-landscape.sh
juju ssh -m $JUJU_CONTROLLER:$JUJU_MODEL landscape-server/0 "bash setup-landscape.sh"
RET=$?

if [ $RET -gt 0 ]; then
    exposeResult "Unable to register against Landscape server, please check your deployment." 1 "false"
fi

result_message="Landscape is now available, to access visit: https://$haproxy/account/standalone/openstack \n\nlogin: $LDS_EMAIL \npassword: $LDS_PASSWORD"

exposeResult "$result_message" 0 "true"

# export LANDSCAPE_API_KEY=$(echo "$output" | python -c "import json; print json.loads(open('/dev/stdin', 
#                'r').read())['LANDSCAPE_API_KEY']")

# landscape-api call BootstrapLDS --json admin_email=stan@example.com admin_name="$ldsver" admin_password=pwd

# LANDSCAPE_API_KEY="anonymous" LANDSCAPE_API_SECRET="anonymous" landscape-api call BootstrapLDS --json admin_email=moo@example.com admin_name="moo" admin_password="password" --uri https://10.0.8.157/api/ --ssl-ca-file /etc/ssl/certs/landscape_server_ca.crt
# {"LANDSCAPE_API_SECRET": "zHwguyk/JE0dIaRNIiqitUNVGm8TuejNsXkYwz08", "LANDSCAPE_API_KEY": "OT70FVBP4HYAKI3ABFCZ"}
#    12 haproxy=$(unitAddress haproxy 0)
# +  13 MYCOMMAND=$(base64 -w0 $SCRIPTPATH/commonrc)
# +  14 #juju scp -m $JUJU_CONTROLLER:$JUJU_MODEL $MYCOMMAND landscape-server/0:setup-landscape.sh
# +  15 juju ssh -m $JUJU_CONTROLLER:$JUJU_MODEL landscape-server/0 "echo $MYCOMMAND | base64 -d | bash"
# +  16 juju ssh -m $JUJU_CONTROLLER:$JUJU_MODEL landscape-server/0 "echo $MYCOMMAND | base64 -d >setup-landscape.sh"


